# Upstream Canary 10%: 90% Blue (v1) e 10% Green (v2)
upstream backend_upstream {
    server api-blue:3000 weight=9 max_fails=2 fail_timeout=2s;
    server api-green:3000 weight=1 max_fails=2 fail_timeout=2s;
}
